/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBalcaoRouteImport } from './routes/admin.balcao'
import { Route as AdminCardapioRouteImport } from './routes/admin.cardapio'
import { Route as AdminComandasRouteImport } from './routes/admin.comandas'
import { Route as AdminCozinhaRouteImport } from './routes/admin.cozinha'
import { Route as AdminHistoricoRouteImport } from './routes/admin.historico'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBalcaoRoute = AdminBalcaoRouteImport.update({
  id: '/balcao',
  path: '/balcao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardapioRoute = AdminCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComandasRoute = AdminComandasRouteImport.update({
  id: '/comandas',
  path: '/comandas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCozinhaRoute = AdminCozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoricoRoute = AdminHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AdminRoute,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/balcao': typeof AdminBalcaoRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/comandas': typeof AdminComandasRoute
  '/admin/cozinha': typeof AdminCozinhaRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/balcao': typeof AdminBalcaoRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/comandas': typeof AdminComandasRoute
  '/admin/cozinha': typeof AdminCozinhaRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/balcao': typeof AdminBalcaoRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/comandas': typeof AdminComandasRoute
  '/admin/cozinha': typeof AdminCozinhaRoute
  '/admin/historico': typeof AdminHistoricoRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/balcao'
    | '/admin/cardapio'
    | '/admin/comandas'
    | '/admin/cozinha'
    | '/admin/historico'
    | '/pedido/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/balcao'
    | '/admin/cardapio'
    | '/admin/comandas'
    | '/admin/cozinha'
    | '/admin/historico'
    | '/pedido/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/admin/balcao'
    | '/admin/cardapio'
    | '/admin/comandas'
    | '/admin/cozinha'
    | '/admin/historico'
    | '/pedido/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PedidoIdRoute: typeof PedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/balcao': {
      id: '/admin/balcao'
      path: '/balcao'
      fullPath: '/admin/balcao'
      preLoaderRoute: typeof AdminBalcaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cardapio': {
      id: '/admin/cardapio'
      path: '/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AdminCardapioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comandas': {
      id: '/admin/comandas'
      path: '/comandas'
      fullPath: '/admin/comandas'
      preLoaderRoute: typeof AdminComandasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cozinha': {
      id: '/admin/cozinha'
      path: '/cozinha'
      fullPath: '/admin/cozinha'
      preLoaderRoute: typeof AdminCozinhaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/historico': {
      id: '/admin/historico'
      path: '/historico'
      fullPath: '/admin/historico'
      preLoaderRoute: typeof AdminHistoricoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBalcaoRoute: typeof AdminBalcaoRoute
  AdminCardapioRoute: typeof AdminCardapioRoute
  AdminComandasRoute: typeof AdminComandasRoute
  AdminCozinhaRoute: typeof AdminCozinhaRoute
  AdminHistoricoRoute: typeof AdminHistoricoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBalcaoRoute: AdminBalcaoRoute,
  AdminCardapioRoute: AdminCardapioRoute,
  AdminComandasRoute: AdminComandasRoute,
  AdminCozinhaRoute: AdminCozinhaRoute,
  AdminHistoricoRoute: AdminHistoricoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PedidoIdRoute: PedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
